NHSO-19656: add acr repo check

diff --git a/.azuredevops/templates/build-deploy-environment.yml b/.azuredevops/templates/build-deploy-environment.yml
--- a/.azuredevops/templates/build-deploy-environment.yml
+++ b/.azuredevops/templates/build-deploy-environment.yml
@@ -250,6 +250,41 @@ stages:
               branchName: $(System.PullRequest.SourceBranch)
             ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
               branchName: $(Build.SourceBranch)
+        - task: AzureCLI@2
+          name: set_version
+          displayName: Set version
+          inputs:
+            azureSubscription: nhsapp-nonlive-terraform-sp
+            scriptType: bash
+            scriptLocation: inlineScript
+            inlineScript: |
+              if [[ "${{ parameters.imageVersionOverride }}" != "None" ]]; then
+                echo "Using version override ${{ parameters.imageVersionOverride }}"
+                version=${{ parameters.imageVersionOverride }}
+                echo "##vso[task.setvariable variable=version]${{ parameters.imageVersionOverride }}"
+                echo "$version"
+              elif [ "$(Build.SourceBranchName)" == "develop" ]; then
+                echo "Versioning for develop"
+                version=$(echo "develop")
+                echo "##vso[task.setvariable variable=version]$version"
+                echo "$version"
+              elif [[ "$(Build.SourceBranchName)" =~ ^v[0-9]+\.[0-9]+ ]]; then
+                echo "Versioning for tag $(Build.SourceBranchName)"
+                version=$(Build.SourceBranchName)
+                echo "##vso[task.setvariable variable=version]$version"
+              else
+                echo "Versioning for pull request (latest git hash) $(Build.SourceBranch)"
+                version=$(az repos pr list --org https://dev.azure.com/nhsapp --project "NHS App" --source-branch $(Build.SourceBranch) | jq -r '.[].lastMergeCommit.commitId')
+                echo "##vso[task.setvariable variable=version]$version"
+                echo "$version"
+                echo "##vso[task.logissue type=warning]If you have recently pushed a new change to your pull request branch, your pods may be in a failed state while the NHS App CI pipeline builds the images."
+              fi
+              if [[ -z "${version}" ]]; then
+                echo "Unable to set version" 
+                exit 1
+              fi
+          env:
+            AZURE_DEVOPS_EXT_PAT: $(AZURE_DEVOPS_EXT_PAT)
         - task: Bash@3
           displayName: 'Update chart version'
           inputs:
@@ -310,6 +345,7 @@ stages:
           inputs:
             targetType: 'inline'
             script: |
+              echo "Installing app version $(version)"
               if [ -f "$(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/vars/zone/$(environment)/namespace/vars-$(environment)-${{ parameters.environmentRefOverride }}.yaml" ]; then
                 echo "Installing with namespace override file"
                 helm upgrade $releaseName $(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/nhsapp/ \
@@ -342,7 +378,7 @@ stages:
                   --set cluster=devuks6
               else
                 echo "Installing without namespace override file"
-                helm upgrade releaseName $(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/nhsapp/ \
+                helm upgrade $releaseName $(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/nhsapp/ \
                   --namespace $(ENVIRONMENT_REF) \
                   --install \
                   --set global.environment="$(ENVIRONMENT_REF)" \
