NHSO-19656: add acr repo check

diff --git a/.azuredevops/templates/build-deploy-environment.yml b/.azuredevops/templates/build-deploy-environment.yml
--- a/.azuredevops/templates/build-deploy-environment.yml
+++ b/.azuredevops/templates/build-deploy-environment.yml
@@ -97,9 +97,78 @@ variables:
     value: 3.2.3
   - name: permanentEnvironments
     value: onboardingsandpit,onboardingaos,authdevelopment,scratch11,preview,
+  - name: version
+    value: develop
 pool:
   vmImage: 'ubuntu-latest'
 stages:
+  - stage: stage_check_image
+    displayName: Check image exists in registry
+    jobs:
+      - job: image_version
+        displayName: 'Get image version and check in registry'
+        steps:
+        - checkout: nhsapp-ops-terraform
+        - checkout: self
+        - template: /pipelines/templates/steps/get_environment_ref.yml@nhsapp-ops-terraform
+          parameters:
+            environmentRefOverride: ${{ parameters.environmentRefOverride }}
+            ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
+              branchName: $(System.PullRequest.SourceBranch)
+            ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
+              branchName: $(Build.SourceBranch)
+        - task: AzureCLI@2
+          name: set_version
+          displayName: Set version
+          inputs:
+            azureSubscription: nhsapp-nonlive-terraform-sp
+            scriptType: bash
+            scriptLocation: inlineScript
+            inlineScript: |
+              if [[ "${{ parameters.imageVersionOverride }}" != "None" ]]; then
+                echo "Using version override ${{ parameters.imageVersionOverride }}"
+                version=${{ parameters.imageVersionOverride }}
+                echo "##vso[task.setvariable variable=version]${{ parameters.imageVersionOverride }}"
+                echo "$version"
+              elif [ "$(Build.SourceBranchName)" == "develop" ]; then
+                echo "Versioning for develop"
+                version=$(echo "develop")
+                echo "##vso[task.setvariable variable=version]$version"
+                echo "$version"
+              elif [[ "$(Build.SourceBranchName)" =~ ^v[0-9]+\.[0-9]+ ]]; then
+                echo "Versioning for tag $(Build.SourceBranchName)"
+                version=$(Build.SourceBranchName)
+                echo "##vso[task.setvariable variable=version]$version"
+              else
+                echo "Versioning for pull request (latest git hash) $(Build.SourceBranch)"
+                version=$(az repos pr list --org https://dev.azure.com/nhsapp --project "NHS App" --source-branch $(Build.SourceBranch) | jq -r '.[].lastMergeCommit.commitId')
+                echo "##vso[task.setvariable variable=version]$version"
+                echo "$version"
+                echo "##vso[task.logissue type=warning]If you have recently pushed a new change to your pull request branch, your pods may be in a failed state while the NHS App CI pipeline builds the images."
+              fi
+              if [[ -z "${version}" ]]; then
+                echo "Unable to set version" 
+                exit 1
+              fi
+              echo "##vso[task.setvariable variable=version;]$version"
+          env:
+            AZURE_DEVOPS_EXT_PAT: $(AZURE_DEVOPS_EXT_PAT)
+        - task: AzureCLI@2
+          displayName: Check repository exists in container registry
+          inputs:
+            azureSubscription: nhsapp-nonlive-terraform-sp
+            scriptType: bash
+            scriptLocation: inlineScript
+            inlineScript: |
+              repoversion=$(az acr repository show --name nhsapp --image nhsonline-web:"${appImageTag}" -o tsv | awk '{print $4}')
+              if [[ "${repoversion}" == "${appImageTag}" ]]; then
+                echo "Image $repoversion found in container registry"
+              else
+                echo "Image $repoversion does not exist in container registry" 
+                exit 1
+              fi
+          env:
+            appImageTag: $(version)
   - stage: stage_plan_apply_scratch_cluster
     displayName: Scratch Cluster Plan And Apply
     jobs:
@@ -181,49 +250,14 @@ stages:
               branchName: $(System.PullRequest.SourceBranch)
             ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
               branchName: $(Build.SourceBranch)
-        - task: AzureCLI@2
-          displayName: Set version
-          inputs:
-            azureSubscription: nhsapp-nonlive-terraform-sp
-            scriptType: bash
-            scriptLocation: inlineScript
-            inlineScript: |
-              if [[ "${{ parameters.imageVersionOverride }}" != "None" ]]; then
-                echo "Using version override ${{ parameters.imageVersionOverride }}"
-                version=${{ parameters.imageVersionOverride }}
-                echo "##vso[task.setvariable variable=version]${{ parameters.imageVersionOverride }}"
-                echo "$version"
-              elif [ "$(Build.SourceBranchName)" == "develop" ]; then
-                echo "Versioning for develop"
-                version=$(echo "develop")
-                echo "##vso[task.setvariable variable=version]$version"
-                echo "$version"
-              elif [[ "$(Build.SourceBranchName)" =~ ^v[0-9]+\.[0-9]+ ]]; then
-                echo "Versioning for tag $(Build.SourceBranchName)"
-                version=$(Build.SourceBranchName)
-                echo "##vso[task.setvariable variable=version]$version"
-              else
-                echo "Versioning for pull request (latest git hash) $(Build.SourceBranch)"
-                version=$(az repos pr list --org https://dev.azure.com/nhsapp --project "NHS App" --source-branch $(Build.SourceBranch) | jq -r '.[].lastMergeCommit.commitId')
-                echo "##vso[task.setvariable variable=version]$version"
-                echo "$version"
-                echo "##vso[task.logissue type=warning]If you have recently pushed a new change to your pull request branch, your pods may be in a failed state while the NHS App CI pipeline builds the images."
-              fi
-              if [[ -z "${version}" ]]; then
-                echo "Unable to set version" 
-                exit 1
-              fi
-          env:
-            AZURE_DEVOPS_EXT_PAT: $(AZURE_DEVOPS_EXT_PAT)
         - task: Bash@3
           displayName: 'Update chart version'
           inputs:
             workingDirectory: $(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/nhsapp/
             targetType: 'inline'
-            script: sed -i -e "s|APPVERSION|$appImageTag|g" Chart.yaml
+            script: sed -i -e "s|APPVERSION|$(version)|g" Chart.yaml
           env:
             chartVersion: $(Build.SourceBranchName)
-            appImageTag: $(version)
         - task: Bash@3
           displayName: 'Set release name'
           inputs:
@@ -278,7 +312,7 @@ stages:
             script: |
               if [ -f "$(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/vars/zone/$(environment)/namespace/vars-$(environment)-${{ parameters.environmentRefOverride }}.yaml" ]; then
                 echo "Installing with namespace override file"
-                helm upgrade $(lowercaseReleaseName) $(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/nhsapp/ \
+                helm upgrade $releaseName $(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/nhsapp/ \
                   --namespace $(ENVIRONMENT_REF) \
                   --install \
                   --set global.environment="$(ENVIRONMENT_REF)" \
@@ -308,7 +342,7 @@ stages:
                   --set cluster=devuks6
               else
                 echo "Installing without namespace override file"
-                helm upgrade $(lowercaseReleaseName) $(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/nhsapp/ \
+                helm upgrade releaseName $(System.DefaultWorkingDirectory)/nhsapp/nhsapp-chart/nhsapp/ \
                   --namespace $(ENVIRONMENT_REF) \
                   --install \
                   --set global.environment="$(ENVIRONMENT_REF)" \
@@ -336,3 +370,5 @@ stages:
                   --set createDefaultPrivateIngress=true \
                   --set cluster=devuks6
               fi
+          env:
+            releaseName: $(lowercaseReleaseName)
