NHSO-18141: Removing references to ImagePullSecrets

diff --git a/.azuredevops/templates/build-deploy-environment.yml b/.azuredevops/templates/build-deploy-environment.yml
--- a/.azuredevops/templates/build-deploy-environment.yml
+++ b/.azuredevops/templates/build-deploy-environment.yml
@@ -174,11 +174,13 @@ stages:
               branchName: $(System.PullRequest.SourceBranch)
             ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
               branchName: $(Build.SourceBranch)
-        - task: Bash@3
+        - task: AzureCLI@2
           displayName: Set version
           inputs:
-            targetType: 'inline'
-            script: |
+            azureSubscription: nhsapp-nonlive-terraform-sp
+            scriptType: bash
+            scriptLocation: inlineScript
+            inlineScript: |
               if [[ "${{ parameters.imageVersionOverride }}" != "None" ]]; then
                 echo "Using version override ${{ parameters.imageVersionOverride }}"
                 version=${{ parameters.imageVersionOverride }}
@@ -195,10 +197,14 @@ stages:
                 echo "##vso[task.setvariable variable=version]$version"
               else
                 echo "Versioning for pull request (latest git hash) $(Build.SourceBranch)"
-                version=$(az repos pr list --source-branch $(Build.SourceBranch) | jq -r '.[].lastMergeCommit.commitId')
+                version=$(az repos pr list --org https://dev.azure.com/nhsapp --project "NHS App" --source-branch $(Build.SourceBranch) | jq -r '.[].lastMergeCommit.commitId')
                 echo "##vso[task.setvariable variable=version]$version"
                 echo "$version"
                 echo "##vso[task.logissue type=warning]If you have recently pushed a new change to your pull request branch, your pods may be in a failed state while the NHS App CI pipeline builds the images."
+              fi
+              if [[ -z "${version}" ]]; then
+                echo "Unable to set version" 
+                exit 1
               fi
           env:
             AZURE_DEVOPS_EXT_PAT: $(AZURE_DEVOPS_EXT_PAT)
